In [2]:
import pandas as pd
import numpy as np

In [3]:
table1 = pd.read_csv('C:/Users/black/Downloads/솔트룩스/data/store_market_data.csv')

In [4]:
table1.head(7)

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,2018-01-02,화,1,1,272369856,정상회원,과실,과일,사과,사과/유(1.5kg),1.0,수지구,풍덕천동,여,45.0,40대,22207,매장C,NaN,10:04
1,2018-01-02,화,1,1,1506656256,정상회원,채소,버섯,느타리버섯,느타리버섯(300g),1.0,수지구,풍덕천동,여,36.0,30대이하,4977,매장C,NaN,10:05
2,2018-01-02,화,1,1,1506656256,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,36.0,30대이하,7083,매장C,NaN,10:05
3,2018-01-02,화,1,1,1023108864,정상회원,반찬,두부/유부,두부,연두부(100g),1.0,수지구,풍덕천동,여,36.0,30대이하,766,매장C,NaN,10:08
4,2018-01-02,화,1,1,1476143616,정상회원,간식,빵,"식빵, 식사대용",아침빵(240g/8개)/매장,1.0,수지구,풍덕천동,여,34.0,30대이하,4403,매장C,NaN,10:09
5,2018-01-02,화,1,1,716128320,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,51.0,50대,7083,매장C,NaN,10:10
6,2018-01-02,화,1,1,743192512,정상회원,채소,과일채소,딸기,딸기/(500g),1.0,수지구,성복동,여,51.0,50대,17038,매장C,NaN,10:12

In [5]:
table1.tail(7)

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
705564,2018-06-30,토,6,26,1278913920,정상회원,수산,해조,김,구운김밥김(10장),1.0,수지구,동천동,여,39.0,30대이하,3446,매장A,NaN,16:43
705565,2018-06-30,토,6,26,867143616,정상회원,간식,빵,"케이크,롤,선물",플레인롤케이크(90g/조각롤),-1.0,기타,기타,여,60.0,60대,-6126,매장A,20180630.0,15:54
705566,2018-06-30,토,6,26,146297344,정상회원,수산,건어물,멸치류,국물멸치(300g),1.0,수지구,성복동,여,51.0,50대,9189,매장A,NaN,17:56
705567,2018-06-30,토,6,26,1532985472,정상회원,수산,해조,미역/다시마,자른다시마(100g),1.0,수지구,동천동,여,63.0,60대,5169,매장A,NaN,14:37
705568,2018-06-30,토,6,26,1532985472,정상회원,반찬,두부/유부,두부,두부(1모:420g),2.0,수지구,동천동,여,63.0,60대,7466,매장A,NaN,14:37
705569,2018-06-30,토,6,26,1209779776,정상회원,간식,과자,스낵,하늘바다새우(60g),1.0,수지구,동천동,여,41.0,40대,3542,매장A,NaN,18:04
705570,2018-06-30,토,6,26,301961920,정상회원,음료,음료,빙과,포도꽁꽁(120ml)/매장용,1.0,수지구,풍덕천동,여,49.0,40대,1914,매장A,NaN,16:36

In [6]:
table1['물품대분류'].unique()

array(['과실', '채소', '축산물', '반찬', '간식', '수산', '주곡', '양념/가루', '음료', '생활용품',
       '서류', '건강', '잡곡', '기타', '주류'], dtype=object)

In [7]:
pd.pivot_table(data = table1, index = '물품대분류',values = '구매금액',aggfunc = 'sum')

             구매금액
물품대분류
간식      852448921
건강      373355801
과실      403550424
기타              0
반찬      528800608
생활용품    412590453
서류       80328779
수산      681997211
양념/가루   498166382
음료      347080915
잡곡      138466267
주곡      270213790
주류       14800659
채소     1049792331
축산물    2053269649

In [8]:
table1.describe()

,공급월,공급주차,회원번호,구매수량,연령,구매금액,반품_원거래일자
count,705571.000000,705571.000000,7.055710e+05,705571.000000,705538.000000,7.055710e+05,1.123400e+04
mean,3.510817,13.500022,7.390639e+08,1.138203,50.756234,1.092004e+04,2.018034e+07
std,1.719153,7.517818,4.251288e+08,0.754448,11.418854,1.670323e+04,5.229237e+02
min,1.000000,1.000000,1.876416e+07,-50.000000,1.000000,-6.662160e+05,2.017121e+07
25%,2.000000,7.000000,3.906917e+08,1.000000,42.000000,4.116000e+03,2.018021e+07
50%,4.000000,13.000000,7.456573e+08,1.000000,49.000000,7.275000e+03,2.018040e+07
75%,5.000000,20.000000,1.045186e+09,1.000000,58.000000,1.263500e+04,2.018052e+07
max,6.000000,26.000000,1.670621e+09,50.000000,108.000000,2.751014e+06,2.018063e+07

In [9]:
table1['성별'] = table1['성별'].replace('남',1).replace('여',0)
table1

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,2018-01-02,화,1,1,272369856,정상회원,과실,과일,사과,사과/유(1.5kg),1.0,수지구,풍덕천동,0.0,45.0,40대,22207,매장C,NaN,10:04
1,2018-01-02,화,1,1,1506656256,정상회원,채소,버섯,느타리버섯,느타리버섯(300g),1.0,수지구,풍덕천동,0.0,36.0,30대이하,4977,매장C,NaN,10:05
2,2018-01-02,화,1,1,1506656256,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,0.0,36.0,30대이하,7083,매장C,NaN,10:05
3,2018-01-02,화,1,1,1023108864,정상회원,반찬,두부/유부,두부,연두부(100g),1.0,수지구,풍덕천동,0.0,36.0,30대이하,766,매장C,NaN,10:08
4,2018-01-02,화,1,1,1476143616,정상회원,간식,빵,"식빵, 식사대용",아침빵(240g/8개)/매장,1.0,수지구,풍덕천동,0.0,34.0,30대이하,4403,매장C,NaN,10:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705566,2018-06-30,토,6,26,146297344,정상회원,수산,건어물,멸치류,국물멸치(300g),1.0,수지구,성복동,0.0,51.0,50대,9189,매장A,NaN,17:56
705567,2018-06-30,토,6,26,1532985472,정상회원,수산,해조,미역/다시마,자른다시마(100g),1.0,수지구,동천동,0.0,63.0,60대,5169,매장A,NaN,14:37
705568,2018-06-30,토,6,26,1532985472,정상회원,반찬,두부/유부,두부,두부(1모:420g),2.0,수지구,동천동,0.0,63.0,60대,7466,매장A,NaN,14:37
705569,2018-06-30,토,6,26,1209779776,정상회원,간식,과자,스낵,하늘바다새우(60g),1.0,수지구,동천동,0.0,41.0,40대,3542,매장A,NaN,18:04
705570,2018-06-30,토,6,26,301961920,정상회원,음료,음료,빙과,포도꽁꽁(120ml)/매장용,1.0,수지구,풍덕천동,0.0,49.0,40대,1914,매장A,NaN,16:36

In [10]:
new_df = table1[table1['구매수량'] < 0]
new_df

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
157,2018-01-02,화,1,1,1479170752,정상회원,축산물,알,유정란,동물복지유정란(10알/국내산),-1.0,수지구,풍덕천동,1.0,78.0,70대이상,-6892,매장C,NaN,15:49
186,2018-01-02,화,1,1,948492096,정상회원,반찬,두부/유부,두부,두부(1모:420g),-2.0,수지구,성복동,1.0,62.0,60대,-7658,매장C,20180102.0,16:47
221,2018-01-02,화,1,1,54078272,정상회원,수산,건어물,멸치류,국물멸치/상(300g),-1.0,수지구,풍덕천동,0.0,51.0,50대,-10912,매장C,20180102.0,18:13
229,2018-01-02,화,1,1,742641280,정상회원,간식,밀가공,면/기타,당면(500g),-1.0,수지구,풍덕천동,0.0,47.0,40대,-9189,매장C,20180102.0,18:25
230,2018-01-02,화,1,1,742641280,정상회원,채소,버섯,목이버섯,목이버섯(200g),-1.0,수지구,풍덕천동,0.0,47.0,40대,-6318,매장C,20180102.0,18:25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705342,2018-06-30,토,6,26,862820992,정상회원,과실,과일,황매실,황매실(남고)/유(5kg),-2.0,수지구,성복동,1.0,53.0,50대,-111036,매장D,20180629.0,13:55
705343,2018-06-30,토,6,26,862820992,정상회원,양념/가루,소스/기타양념,기타양념,유기농설탕(5kg),-1.0,수지구,성복동,1.0,53.0,50대,-31588,매장D,20180629.0,13:55
705344,2018-06-30,토,6,26,862820992,정상회원,축산물,소,한우(냉장),설도다짐육(안심대안/200g/신선육),-1.0,수지구,성복동,1.0,53.0,50대,-16464,매장D,20180629.0,13:55
705430,2018-06-30,토,6,26,56646976,정상회원,간식,밀가공,간편조리면,동치미냉면육수(330g),-5.0,수지구,죽전동,0.0,66.0,60대,-12444,매장B,20180615.0,14:29
705565,2018-06-30,토,6,26,867143616,정상회원,간식,빵,"케이크,롤,선물",플레인롤케이크(90g/조각롤),-1.0,기타,기타,0.0,60.0,60대,-6126,매장A,20180630.0,15:54